# Linear Regression

Welcome to your first assignment. This exercise gives you a brief introduction to linear regression. The exercise is to be implemented in Python. Even if you've used Python before, this will help familiarize you with functions we'll need.  

**Instructions:**
- You will be using Python 3.
- Avoid using for-loops and while-loops, unless you are explicitly told to do so.
- Do not modify the (# GRADED FUNCTION [function name]) comment in some cells. Your work would not be graded if you change this. Each cell containing that comment should only contain one function.
- After coding your function, run the cell right below it to check if your result is correct.

**After this assignment you will:**
- Be able to implement linear regression model using statsmodels, scikit-learn, and tensorflow
- Work with simulated non-linear dataset
- Compare model performance (quality of fit) of both models

Let's get started!

## About iPython Notebooks ##

iPython Notebooks are interactive coding environments embedded in a webpage. You will be using iPython notebooks in this class. You only need to write code between the ### START CODE HERE ### and ### END CODE HERE ### comments. After writing your code, you can run the cell by either pressing "SHIFT"+"ENTER" or by clicking on "Run Cell" (denoted by a play symbol) in the upper bar of the notebook. 

We will often specify "(≈ X lines of code)" in the comments to tell you about how much code you need to write. It is just a rough estimate, so don't feel bad if your code is longer or shorter.

In [16]:
import os
import numpy as np

try:
    import matplotlib.pyplot as plt
    %matplotlib inline
except: pass

import pandas as pd

import tensorflow as tf
from tensorflow.python.layers import core as core_layers
try:
    from mpl_toolkits.mplot3d import Axes3D
except: pass

In [17]:
def reset_graph(seed=42):
    """
    Utility function to reset current tensorflow computation graph
    and set the random seed 
    """
    # to make results reproducible across runs
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

## We use artificial data for the following two specifications of regression:

### Linear Regression

$ y(x) = a + b_1 \cdot X_1 + b_2 \cdot X_2 + b_3 \cdot X_3 + \sigma \cdot \varepsilon $ 

where $ \varepsilon \sim N(0, 1) $ is a Gaussian noise, and $ \sigma $ is its volatility, 
with the following choice of parameters:

$ a = 1.0 $

$ b_1, b_2, b_3 = (0.5, 0.2, 0.1) $

$ \sigma = 0.1 $

$ X_1, X_2, X_3 $ will be uniformally distributed in $ [-1,1] $

### Non-Linear Regression

$ y(x) = a + w_{00} \cdot X_1 + w_{01} \cdot X_2 + w_{02} \cdot X_3 + + w_{10} \cdot X_1^2 
+ w_{11} \cdot X_2^2 + w_{12} \cdot X_3^2 +  \sigma \cdot \varepsilon $ 

where

$ w = [[1.0, 0.5, 0.2],[0.5, 0.3, 0.15]]  $

and the rest of parameters is as above, with the same values of $ X_i $

### Generate Data

In [18]:
def generate_data(n_points=10000, n_features=3, use_nonlinear=True, 
                    noise_std=0.1, train_test_split = 4):
    """
    Arguments:
    n_points - number of data points to generate
    n_features - a positive integer - number of features
    use_nonlinear - if True, generate non-linear data
    train_test_split - an integer - what portion of data to use for testing
    
    Return:
    X_train, Y_train, X_test, Y_test, n_train, n_features
    """
    
    # Linear data or non-linear data?
    if use_nonlinear:
        weights = np.array([[1.0, 0.5, 0.2],[0.5, 0.3, 0.15]])
    else:
        weights = np.array([1.0, 0.5, 0.2])
        
    bias = np.ones(n_points).reshape((-1,1))
    low = - np.ones((n_points,n_features),'float')
    high = np.ones((n_points,n_features),'float')
    
    X = np.random.uniform(low=low, high=high)
    noise = np.random.normal(size=(n_points, 1))
    noise_std = 0.1
    
    if use_nonlinear:
        Y = (weights[0,0] * bias + np.dot(X, weights[0, :]).reshape((-1,1)) + 
             np.dot(X*X, weights[1, :]).reshape([-1,1]) +
             noise_std * noise)
    else:
        Y = (weights[0] * bias + np.dot(X, weights[:]).reshape((-1,1)) + 
             noise_std * noise)
    
    n_test = int(n_points/train_test_split)
    n_train = n_points - n_test
    
    X_train = X[:n_train,:]
    Y_train = Y[:n_train].reshape((-1,1))

    X_test = X[n_train:,:]
    Y_test = Y[n_train:].reshape((-1,1))
    
    return X_train, Y_train, X_test, Y_test, n_train, n_features

X_train, Y_train, X_test, Y_test, n_train, n_features = generate_data(use_nonlinear=False)
X_train.shape, Y_train.shape

((7500, 3), (7500, 1))

### Linear Regression with Numpy

In [19]:
# GRADED FUNCTION: numpy_lin_regress
def numpy_lin_regress(X_train, Y_train):
    """
    numpy_lin_regress - Implements linear regression model using numpy module
    Arguments:
    X_train  - np.array of size (n by k) where n is number of observations 
                of independent variables and k is number of variables
    Y_train - np.array of size (n by 1) where n is the number of observations of dependend variable
    
    Return:
    np.array of size (k+1 by 1) of regression coefficients
    """
    # number of features
    ndim = X_train.shape[1] 
    ### START CODE HERE ### (≈ 3 lines of code)
    design_matrix = np.insert(X_train, 0, [1.], axis=1)
    theta_numpy = np.linalg.lstsq(design_matrix,Y_train)[0]  # replace this line with your calculation
    ### END CODE HERE ###
    return theta_numpy

In [20]:
### GRADED PART (DO NOT EDIT) ###
theta_numpy = numpy_lin_regress(X_train, Y_train)
theta_numpy.squeeze()
### GRADED PART (DO NOT EDIT) ###

array([ 1.00162408,  0.99816368,  0.5042376 ,  0.20078698])

### Linear Regression with Sklearn

In [21]:
# GRADED FUNCTION: sklearn_lin_regress
def sklearn_lin_regress(X_train, Y_train):
    """
    Arguments:
    X_train  - np.array of size (n by k) where n is number of observations 
                of independent variables and k is number of variables
    Y_train - np.array of size (n by 1) where n is the number of observations of dependend variable
    
    Return:
    np.array of size (k+1 by 1) of regression coefficients
    """
    ndim = X_train.shape[1] 
    ### START CODE HERE ### (≈ 3 lines of code)
    from sklearn import linear_model
    
    model = linear_model.LinearRegression()
    fitted_model = model.fit(X_train, Y_train)
    print("The model intercept is ", fitted_model.intercept_)
    print("The model coefficients are: ",fitted_model.coef_)
    theta_sklearn = np.insert(fitted_model.coef_, 0, fitted_model.intercept_,axis=1) # replace this line with your calculation
    ### END CODE HERE ###
    return theta_sklearn

In [22]:
### GRADED PART (DO NOT EDIT) ###
theta_sklearn = sklearn_lin_regress(X_train, Y_train)
theta_sklearn.squeeze()
### GRADED PART (DO NOT EDIT) ###

The model intercept is  [ 1.00162408]
The model coefficients are:  [[ 0.99816368  0.5042376   0.20078698]]


array([ 1.00162408,  0.99816368,  0.5042376 ,  0.20078698])

### Linear Regression with Tensorflow

In [48]:
# GRADED FUNCTION: tf_lin_regress
def tf_lin_regress(X_train, Y_train):
    """
    Arguments:
    X_train  - np.array of size (n by k) where n is number of observations 
                of independent variables and k is number of variables
    Y_train - np.array of size (n by 1) where n is the number of observations of dependend variable
    
    Return:
    np.array of size (k+1 by 1) of regression coefficients
    """
    ndim = X_train.shape[1] 
    ### START CODE HERE ### (≈ 7-8 lines of code)
    import tensorflow as tf
    tf.logging.set_verbosity(tf.logging.ERROR)
    feature_columns = [tf.feature_column.numeric_column("x", shape=[3])]
    model = tf.estimator.LinearRegressor(feature_columns=feature_columns) 
    input_fn = tf.estimator.inputs.numpy_input_fn(
    {"x": X_train}, Y_train, shuffle=True)
    
    #train_input_fn = tf.estimator.inputs.numpy_input_fn(
    #{"x": X_train}, Y_train, batch_size=4, num_epochs=1000, shuffle=False)
    #eval_input_fn = tf.estimator.inputs.numpy_input_fn(
    #{"x": X_test}, Y_test, batch_size=4, num_epochs=1000, shuffle=False)
    
    model.train(input_fn=input_fn, steps=1000000)
    #print(model.get_variable_names()) 
    variables = []
    for i in [0,1,4]:
        variable_name = model.get_variable_names()[i]
        variable_value = model.get_variable_value(variable_name)
        print('{0}: {1}'.format(variable_name,variable_value))
        variables.append(variable_value)
    theta_value = np.insert(model.get_variable_value(model.get_variable_names()[4]),0,model.get_variable_value(model.get_variable_names()[1]))  # replace this line with your calculation
    ### END CODE HERE ###
    return theta_value

In [49]:
### GRADED PART (DO NOT EDIT) ###
theta_tf = tf_lin_regress(X_train, Y_train)
theta_tf.squeeze()
### GRADED PART (DO NOT EDIT) ###

global_step: 59
linear/linear_model/bias_weights: [ 0.99782407]
linear/linear_model/x/weights: [[ 1.0029664 ]
 [ 0.49972922]
 [ 0.19648392]]


array([ 0.99782407,  1.0029664 ,  0.49972922,  0.19648392], dtype=float32)

In [38]:
# GRADED FUNCTION: run_normal_eq
def run_normal_eq(X_train, Y_train, X_test, Y_test, learning_rate=0.05):
    """
    Implements normal equation using tensorflow, trains the model using training data set
    Tests the model quality by computing mean square error (MSE) of the test data set
    
    Arguments:
    X_train  - np.array of size (n by k) where n is number of observations 
                of independent variables and k is number of variables
    Y_train - np.array of size (n by 1) where n is the number of observations of dependend variable
    
    X_test  - np.array of size (n by k) where n is number of observations 
                of independent variables and k is number of variables
    Y_test - np.array of size (n by 1) where n is the number of observations of dependend variable
    
    
    Return a tuple of:
        - np.array of size (k+1 by 1) of regression coefficients
        - mean square error (MSE) of the test data set
        - mean square error (MSE) of the training data set
    """
    ndim = X_train.shape[1]
    lr_mse_train = 0.
    lr_mse_test = 0.
    ### START CODE HERE ### (≈ 20 lines of code)
    

    X = tf.constant(np.c_[np.ones((X_train.shape[0], 1)), X_train], dtype=tf.float32, name="X")
    y_train = tf.constant(Y_train, dtype=tf.float32, name="yhat")
    y_test = tf.constant(Y_test, dtype=tf.float32, name="y-test")
    X_test = tf.constant(np.c_[np.ones((X_test.shape[0], 1)), X_test], dtype=tf.float32, name="X-test")
    
    XT = tf.transpose(X)
    theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y_train)
   
    lr_mse_train = tf.sqrt(tf.reduce_sum(tf.square(tf.subtract(tf.matmul(X,theta),y_train))))
    
    lr_mse_test = tf.sqrt(tf.reduce_sum(tf.square(tf.subtract(tf.matmul(X_test,theta),y_test))))
    
    with tf.Session() as sess:
        theta_value = theta.eval()
        lr_mse_train = lr_mse_train.eval()
        yhat_test = tf.matmul(X_test,theta_value)
        lr_mse_test = lr_mse_test.eval()
    
    
    
    ### END CODE HERE ###
    return theta_value, lr_mse_train, lr_mse_test

### (DO NOT EDIT) ###
theta_value, lr_mse_train, lr_mse_test = run_normal_eq(X_train, Y_train, X_test, Y_test)
### (DO NOT EDIT) ###

In [39]:
### GRADED PART (DO NOT EDIT) ###
theta_value.squeeze()
### GRADED PART (DO NOT EDIT) ###

array([ 1.00162387,  0.9981637 ,  0.50423741,  0.20078699], dtype=float32)

In [27]:
# GRADED FUNCTION: run_mle
def run_mle(X_train, Y_train, X_test, Y_test, learning_rate=0.05, num_iter=5000):
    """
    Maximum likelihood Estimate (MLE)
    Tests the model quality by computing mean square error (MSE) of the test data set
    
    Arguments:
    X_train  - np.array of size (n by k) where n is number of observations 
                of independent variables and k is number of variables
    Y_train - np.array of size (n by 1) where n is the number of observations of dependend variable
    
    X_test  - np.array of size (n by k) where n is number of observations 
                of independent variables and k is number of variables
    Y_test - np.array of size (n by 1) where n is the number of observations of dependend variable
    
    
    Return a tuple of:
        - np.array of size (k+1 by 1) of regression coefficients
        - mean square error (MSE) of the test data set
        - mean square error (MSE) of the training data set
    """
    # create an instance of the Linear Regression model class  
    ndim = X_train.shape[1]
    loss = 0.
    std_model = 0.
    ### START CODE HERE ### (≈ 20 lines of code)
    # Placeholder that is fed input data.
    X_in = tf.placeholder(tf.float32, [None, ndim], "X_in")
    
    #PLacehold that is fed observed results.
    y_in = tf.placeholder(tf.float32, [None, 1], "y_in")
    
    #Specify model y= wX+b
    w = tf.Variable(tf.random_normal((ndim, 1)), name="w") 
    b = tf.Variable(tf.constant(0., shape=None), name="b")
    yhat = tf.add(tf.matmul(X_in,w), b, name="yhat")
    
    # The loss function: we are minimizing square root of mean 
    loss_op = tf.reduce_mean(tf.square(tf.subtract(y_in, yhat)), name="loss")
    train_op = tf.train.GradientDescentOptimizer(0.3).minimize(loss_op)
    
    #Test the fitted model
    
    y_test = tf.constant(Y_test, dtype=tf.float32, name="y-test")
    X_test = tf.constant( X_test, dtype=tf.float32, name="X-test")
    std_model = tf.reduce_mean(tf.square(tf.subtract(tf.add(tf.matmul(X_test,w),b),y_test)))
       
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        for step in range(1000):
            loss, weights, bees, extra = sess.run([loss_op, w, b, train_op], feed_dict={
              X_in: X_train, 
              y_in: Y_train
            })
        std_model = sess.run(std_model)
        
        
        
    weights = np.insert(weights,0,bees)
    print(weights, loss, std_model)
    ### END CODE HERE ###
    return weights, loss, std_model

weights, loss, std_model = run_mle(X_train, Y_train, X_test, Y_test)

[ 1.00162399  0.99816382  0.50423747  0.20078699] 0.00988956 0.00986643


In [28]:
### GRADED PART (DO NOT EDIT) ###
weights.squeeze()
### GRADED PART (DO NOT EDIT) ###

array([ 1.00162399,  0.99816382,  0.50423747,  0.20078699], dtype=float32)